BLIZZARD® STARCRAFT® II AI AND MACHINE LEARNING LICENSE

IMPORTANT NOTICE:

YOU SHOULD CAREFULLY READ THIS AGREEMENT (THE “AGREEMENT”) BEFORE INSTALLING OR USING 
BLIZZARD’S (“BLIZZARD”) STARCRAFT II AI AND MACHINE LEARNING SOFTWARE AND ENVIRONMENT (THE 
“SOFTWARE”).  IF YOU DO NOT AGREE WITH ALL OF THE TERMS OF THIS AGREEMENT, YOU MAY NOT INSTALL 
OR OTHERWISE ACCESS THE SOFTWARE.

Subject to the terms of this Agreement, your use of the Software is governed by Blizzard’s End 
User License Agreement (“EULA”), which is incorporated by reference herein and is available 
for review here. (http://us.blizzard.com/en-us/company/legal/eula.html)  Please carefully 
review the EULA and this Agreement prior to installing or using the Software.  IF YOU DO NOT 
AGREE TO THE TERMS OF THE EULA AND THIS AGREEMENT, YOU ARE NOT PERMITTED TO INSTALL, COPY, OR 
USE THE SOFTWARE.

1.  Use Of The Software.
    A.  AI Testing And Machine Learning Use Only: Subject to your compliance with this 
	Agreement, Blizzard grants you a limited, revocable, non-sublicensable license to use the 
	Software for purposes of AI testing, machine learning, and related research only.
    B.  Blizzard Account Not Required: Notwithstanding the requirements of Section 1.A of the 
	EULA, creation of a Blizzard Account is not required in order to use the Software.  Legal 
	entities other than natural persons are authorized to use the Software.  However, other 
	than as specifically excepted in this Agreement, the remaining provisions and requirements 
	of the EULA are controlling.
    C.  EULA Exceptions: The terms of Blizzard’s EULA govern your use of the Software, subject 
	to the following narrow exceptions:
        i.   Derivative Works: Section 1.C.i of the EULA shall not be read to prohibit the 
	     authorized use of the Software or data generated or collected from such use. However, 
	     no portion of this Agreement shall give you the right to create, distribute, or 
	     otherwise exploit unauthorized derivative works of the Software.
        ii.  Automation: The provisions of Section 1.C.ii of the EULA prohibiting the use of 
	     automation processes or software do not apply to use of the Software.
        iii. Commercial Use:  The provisions of Section 1.C.iii of the EULA govern your use 
	     of the Software, except that you are authorized to use and exploit data derived from 
	     using the Software in connection with AI and machine learning programs for personal or 
	     internal use, despite that such use of the data may ultimately be for a commercial 
	     purpose.  You may not otherwise use or exploit the Software for any commercial purpose.
        iv.  Data Mining: The provisions of Section 1.C.iv of the EULA shall not prohibit the 
	     authorized use of the Software or data generated or collected from such use. 
        v.   Matchmaking: The provisions of Section 1.C.vi of the EULA shall not prohibit the 
	     authorized use of the Software or data generated or collected from such use.
2.  Ownership.
    A.  The provisions of Section 2 of the EULA apply in full force to the Software (including 
	any derivatives thereof), except that you may own and use AI or machine learning data 
	generated by or collected through the authorized use of the Software. 
